include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/trivy.yml

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      when: always
    - when: never

stages:
  - download
  - build
  - scan

check:
  stage: download
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
  parallel:
    matrix:
      - { VERSION: 'latest', GIT_STRATEGY: 'none' }
      - { VERSION: 'prev', GIT_STRATEGY: 'none' }
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  before_script:
    - apk add --no-cache grep wget curl
    - touch ${VERSION}.txt
  script:
    - if [ "$VERSION" == "latest" ]; then REMOTE_VERSION=$(wget -qO- https://golang.org/dl/ | grep -oP "(?<=go)([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.linux)" | uniq | head -n2 | awk 'NR==1{print $0}'); fi
    - if [ "$VERSION" != "latest" ]; then REMOTE_VERSION=$(wget -qO- https://golang.org/dl/ | grep -oP "(?<=go)([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.linux)" | uniq | head -n2 | awk 'NR==2{print $0}'); fi
    - LOCAL_VERSION=$(cat ${VERSION}.txt)
    - |
      if [ ! -z "${FORCE_BUILD+x}" ] || [ "${REMOTE_VERSION}" != "${LOCAL_VERSION}" ]; then
        echo "${REMOTE_VERSION} and ${LOCAL_VERSION} differ. Running build."
        curl -F token=${CI_JOB_TOKEN} -F ref=master -F "variables[V_TYPE]=${VERSION}" -F "variables[VERSION]=${REMOTE_VERSION}" -F "variables[BUILD]=true" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline
      else
        echo "${REMOTE_VERSION} and ${LOCAL_VERSION} where equal. Running scan."
        curl -F token=${CI_JOB_TOKEN} -F ref=master -F "variables[OS_TYPE]=${OS_TYPE}" -F "variables[V_TYPE]=${VERSION}" -F "variables[VERSION]=${REMOTE_VERSION}" -F "variables[SCAN]=true" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline
      fi
  cache:
    paths:
      - ${VERSION}.txt
    policy: pull

download:
  stage: download
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - echo "Downloading version ${VERSION} (${V_TYPE})"
    - apk add --no-cache libxml2-utils grep wget
    - SHASUM=$(wget -qO- https://golang.org/dl/ | xmllint --html --xpath "//a[contains(@class, 'download') and contains(@href, 'go${VERSION}.src.tar.gz') and not(contains(@class, 'downloadBox'))]/parent::td/following-sibling::td[5]/tt/text()" - 2>/dev/null)
    - echo "${SHASUM} go${VERSION}.src.tar.gz" >> sha256sum.txt
    - wget "https://golang.org/dl/go${VERSION}.src.tar.gz"
    - sha256sum -c sha256sum.txt
  artifacts:
    paths:
      - go${VERSION}.src.tar.gz
    expire_in: 1 day
    when: on_success
  rules:
    - if: "$BUILD"
      when: always
    - when: never

build:
  stage: build
  needs:
    - download
  parallel:
    matrix:
      - { OS_TYPE: 'alpine' }
      - { OS_TYPE: 'ubuntu' }
      - { OS_TYPE: 'debian' }
  trigger:
    include: ".gitlab/build.yml"
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    TYPE: $V_TYPE
    VERSION: $VERSION
    OS_TYPE: $OS_TYPE
  rules:
    - if: "$BUILD"
      when: on_success
    - when: never

scan:
  stage: scan
  extends: .container_scanning
  rules:
    - if: "$SCAN"
      when: always
    - when: never
  variables:
    GIT_STRATEGY: none
  before_script:
    - TAG=":${VERSION}"
    - if [ $OS_TYPE != ${ALPINE} ]; then TAG="/${OS_TYPE}/${VERSION}:"; fi
    - SCANNING_IMAGE_NAME="${CI_REGISTRY_IMAGE}${TAG}"
