stages:
  - download
  - build

########################################################################################################################
#                                                                                                                      #
#                                                  Bootstrap build.                                                    #
#                                                                                                                      #
# Due to the fact that Go requires Go to compile, a bootstrap image is required. The following build steps are made to #
# only build the bootstrap file and push it to the registry. It's only built when required, not always.                #
#                                                                                                                      #
########################################################################################################################

download:bootstrap:
  stage: download
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
    SHA: "f4ff5b5eb3a3cae1c993723f3eab519c5bae18866b5e5f96fe1102f0cb5c3e52  go1.4-bootstrap-20171003.tar.gz"
  script:
    - wget https://dl.google.com/go/go1.4-bootstrap-20171003.tar.gz
    - echo "${SHA}" > shasum.txt
    - sha256sum -c shasum.txt
  artifacts:
    paths:
      - go1.4-bootstrap-20171003.tar.gz
    expire_in: 5 hours
  only:
    refs:
      - bootstrap

build:bootstrap:alpine:
  stage: build
  dependencies:
    - download:bootstrap
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  script:
    - docker build ${CI_REGISTRY_IMAGE}:bootstrap -f Alpine/Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}:bootstrap
  only:
    refs:
      - bootstrap
  tags: [ jitesoft, amd64 ]

build:bootstrap:ubuntu:
  stage: build
  dependencies:
    - download:bootstrap
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu:bootstrap -f Ubuntu/Dockerfile .
    - docker push -t ${CI_REGISTRY_IMAGE}/ubuntu:bootstrap
  only:
    refs:
      - bootstrap
  tags: [ jitesoft, amd64 ]
