include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

variables:
  ARCHITECTURES: "linux/amd64,linux/arm64"

stages:
  - pre
  - download
  - build
  - containerize
  - scan

download:versions:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: pre
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache libxml2-utils grep
  script:
    - VERSIONS=$(wget -qO- https://golang.org/dl/ | grep -oP "(?<=go)([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.linux)" | uniq | head -n2)
    - |
      for VERSION in ${VERSIONS}; do
        OUTPUT=$(wget -qO- https://golang.org/dl/ | xmllint --html --xpath "//a[contains(@class, 'download') and contains(@href, 'go${VERSION}.src.tar.gz') and not(contains(@class, 'downloadBox'))]/parent::td/following-sibling::td[5]/tt/text()" - 2>/dev/null)
        echo "${OUTPUT} go${VERSION}.src.tar.gz" >> sha256sum.txt
      done
  artifacts:
    paths:
      - sha256sum.txt
    expire_in: 1 day
  tags: [ jitesoft ]
  only:
    refs:
      - master

download:src:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  variables:
    GIT_STRATEGY: none
  dependencies:
    - download:versions
  before_script:
    - apk add --no-cache coreutils
  script:
    - cat sha256sum.txt
    - |
      while read -r line
      do
        set -- $line
        wget "https://dl.google.com/go/${2}"
      done <"sha256sum.txt"
    - sha256sum -c sha256sum.txt
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/*.src.tar.gz
    expire_in: 1 day
  tags: [ jitesoft ]
  only:
    refs:
      - master

.build:base:
  needs:
    - download:src
    - download:versions
  stage: build
  script:
    - |
      if [ "${TYPE}" == "latest" ]; then
        FILE=$(cat sha256sum.txt | awk '{print $2}' | head -1)
        VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')
      else
        FILE=$(cat sha256sum.txt | awk '{print $2}' | tail -1)
        VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')
      fi
    - echo "${TYPE} ${VERSION}"
    - mkdir /opt/src
    - tar -xzhf go${VERSION}.src.tar.gz
    - cd go/src
    - ./make.bash
    - rm -rf /usr/local/go/pkg/bootstrap
    - rm -rf /usr/local/go/pkg/obj
  after_script:
    - $(cd /usr/local/go && tar -czf go-${ARCH}.tar.gz *)
  artifacts:
    paths:
      - go-${ARCH}.tar.gz
    expire_in: 1 day
  only:
    refs:
      - master

.build:alpine:
  extends: .build:base
  image: registry.gitlab.com/jitesoft/dockerfiles/go/bootstrap:alpine
  before_script:
    - apk add --no-cache git gcc openssl ca-certificates musl-dev bash

.build:debian:
  extends: .build:base
  image: registry.gitlab.com/jitesoft/dockerfiles/go/bootstrap:debian
  before_script:
    - apt-get update
    - apt-get install -y git gcc openssl ca-certificates

.build:ubuntu:
  extends: .build:base
  image: registry.gitlab.com/jitesoft/dockerfiles/go/bootstrap:ubuntu
  before_script:
    - apt-get update
    - apt-get install -y git gcc openssl ca-certificates

build:alpine:amd:latest:
  extends: .build:alpine
  variables:
    ARCH: amd64
    TYPE: latest
  tags:
    - native-amd64

build:alpine:amd:prev:
  extends: .build:alpine
  variables:
    ARCH: amd64
    TYPE: prev
  tags:
    - native-amd64

build:alpine:arm:latest:
  extends: .build:alpine
  variables:
    ARCH: arm64
    TYPE: latest
  tags:
    - native-aarch64

build:alpine:arm:prev:
  extends: .build:alpine
  variables:
    ARCH: arm64
    TYPE: prev
  tags:
    - native-aarch64

build:ubuntu:amd:latest:
  extends: .build:ubuntu
  variables:
    ARCH: amd64
    TYPE: latest
  tags:
    - native-amd64

build:ubuntu:amd:prev:
  extends: .build:ubuntu
  variables:
    ARCH: amd64
    TYPE: prev
  tags:
    - native-amd64

build:ubuntu:arm:latest:
  extends: .build:ubuntu
  variables:
    ARCH: arm64
    TYPE: latest
  tags:
    - native-aarch64

build:ubuntu:arm:prev:
  extends: .build:ubuntu
  variables:
    ARCH: arm64
    TYPE: prev
  tags:
    - native-aarch64

build:debian:amd:latest:
  extends: .build:debian
  variables:
    ARCH: amd64
    TYPE: latest
  tags:
    - native-amd64

build:debian:amd:prev:
  extends: .build:debian
  variables:
    ARCH: amd64
    TYPE: prev
  tags:
    - native-amd64

build:debian:arm:latest:
  extends: .build:debian
  variables:
    ARCH: arm64
    TYPE: latest
  tags:
    - native-aarch64

build:debian:arm:prev:
  extends: .build:debian
  variables:
    ARCH: arm64
    TYPE: prev
  tags:
    - native-aarch64

.containerize:alpine:
  stage: containerize
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - mkdir bin
    - mv *.tar.gz bin/
    - VERSION_SHORT="${VERSION}"
    - OC=$(echo ${VERSION} | awk -F"." '{print NF-1}')
    - if [ "$OC" = "2" ]; then VERSION_SHORT=$(echo ${VERSION} | cut -d'.' -f1,2); fi
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE},jitesoft/go", "${TAGS},${VERSION},${VERSION_SHORT}")
    - docker buildx build --platform ${ARCHITECTURES} --progress plain --push ${TAG_LIST} --build-arg VERSION=${VERSION} -f Alpine/Dockerfile .
  only:
    refs:
      - master
  tags: [ jitesoft, buildx, protected ]

.containerize:ubuntu:
  stage: containerize
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - mkdir bin
    - mv *.tar.gz bin/
    - VERSION_SHORT="${VERSION}"
    - OC=$(echo ${VERSION} | awk -F"." '{print NF-1}')
    - if [ "$OC" = "2" ]; then VERSION_SHORT=$(echo ${VERSION} | cut -d'.' -f1,2); fi
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/ubuntu", "${TAGS},${VERSION}${VERSION_SHORT}")
    - TAG_LIST_HUB=$(helper "jitesoft/go", "${TAGS}-ubuntu,${VERSION}-ubuntu,${VERSION_SHORT}-ubuntu")
    - docker buildx build --platform ${ARCHITECTURES} --progress plain --push ${TAG_LIST} ${TAG_LIST_HUB} --build-arg VERSION=${VERSION} -f Ubuntu/Dockerfile .
  only:
    refs:
      - master
  tags: [ jitesoft, buildx, protected ]

.containerize:debian:
  stage: containerize
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - mkdir bin
    - mv *.tar.gz bin/
    - VERSION_SHORT="${VERSION}"
    - OC=$(echo ${VERSION} | awk -F"." '{print NF-1}')
    - if [ "$OC" = "2" ]; then VERSION_SHORT=$(echo ${VERSION} | cut -d'.' -f1,2); fi
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/debian", "${TAGS},${VERSION}${VERSION_SHORT}")
    - TAG_LIST_HUB=$(helper "jitesoft/go", "${TAGS}-debian,${VERSION}-debian,${VERSION_SHORT}-debian")
    - docker buildx build --platform ${ARCHITECTURES} --progress plain --push ${TAG_LIST} ${TAG_LIST_HUB} --build-arg VERSION=${VERSION} -f Debian/Dockerfile .
  only:
    refs:
      - master
  tags: [ jitesoft, buildx, protected ]

containerize:current:ubuntu:
  stage: containerize
  needs:
    - build:ubuntu:arm:latest
    - build:ubuntu:amd:latest
    - download:versions
  variables:
    TAGS: "latest"
  extends: .containerize:ubuntu
  before_script:
    - apk add --no-cache grep
    - FILE=$(cat sha256sum.txt | awk '{print $2}' | head -1)
    - VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')

containerize:prev:ubuntu:
  stage: containerize
  needs:
    - build:ubuntu:arm:prev
    - build:ubuntu:amd:prev
    - download:versions
  variables:
    TAGS: "prev"
  extends: .containerize:debian
  before_script:
    - apk add --no-cache grep
    - FILE=$(cat sha256sum.txt | awk '{print $2}' | tail -1)
    - VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')

containerize:current:debian:
  stage: containerize
  needs:
    - build:debian:arm:latest
    - build:debian:amd:latest
    - download:versions
  variables:
    TAGS: "latest"
  extends: .containerize:debian
  before_script:
    - apk add --no-cache grep
    - FILE=$(cat sha256sum.txt | awk '{print $2}' | head -1)
    - VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')

containerize:prev:debian:
  stage: containerize
  needs:
    - build:debian:arm:prev
    - build:debian:amd:prev
    - download:versions
  variables:
    TAGS: "prev"
  extends: .containerize:debian
  before_script:
    - apk add --no-cache grep
    - FILE=$(cat sha256sum.txt | awk '{print $2}' | tail -1)
    - VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')

containerize:current:alpine:
  stage: containerize
  needs:
    - build:alpine:arm:latest
    - build:alpine:amd:latest
    - download:versions
  variables:
    TAGS: "latest"
  extends: .containerize:alpine
  before_script:
    - apk add --no-cache grep
    - FILE=$(cat sha256sum.txt | awk '{print $2}' | head -1)
    - VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')

containerize:prev:alpine:
  needs:
    - build:alpine:arm:prev
    - build:alpine:amd:prev
    - download:versions
  stage: containerize
  variables:
    TAGS: "prev"
  extends: .containerize:alpine
  before_script:
    - apk add --no-cache grep
    - FILE=$(cat sha256sum.txt | awk '{print $2}' | tail -1)
    - VERSION=$(echo ${FILE} | grep -oP '([0-9]{0,3}[.][0-9]{0,3}([.][0-9]{0,3})?)(?=.src.tar.gz)')

scan:current:ubuntu:
  needs:
    - containerize:current:ubuntu
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/ubuntu:latest"
    GIT_STRATEGY: none

scan:prev:ubuntu:
  needs:
    - containerize:prev:ubuntu
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/ubuntu:prev"
    GIT_STRATEGY: none

scan:current:debian:
  needs:
    - containerize:current:debian
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/debian:latest"
    GIT_STRATEGY: none

scan:prev:debian:
  needs:
    - containerize:prev:debian
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/debian:prev"
    GIT_STRATEGY: none

scan:current:alpine:
  needs:
    - containerize:current:alpine
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
    GIT_STRATEGY: none

scan:prev:alpine:
  needs:
    - containerize:prev:alpine
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:prev"
    GIT_STRATEGY: none
