stages:
  - download
  - build

variables:
  DOCKER_BUILDKIT: 1
  ARCHITECTURES: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386"


########################################################################################################################
#                                                                                                                      #
#                                                  Bootstrap build.                                                    #
#                                                                                                                      #
# Due to the fact that Go requires Go to compile, a bootstrap image is required. The following build steps are made to #
# only build the bootstrap file and push it to the registry. It's only built when required, not always.                #
#                                                                                                                      #
########################################################################################################################

download:bootstrap:
  stage: download
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
    SHA: "f4ff5b5eb3a3cae1c993723f3eab519c5bae18866b5e5f96fe1102f0cb5c3e52  go1.4-bootstrap-20171003.tar.gz"
    SHA2: "afc1e12f5fe49a471e3aae7d906c73e9d5b1fdd36d52d72652dde8f6250152fb  go1.11.src.tar.gz"
  script:
    - wget https://dl.google.com/go/go1.4-bootstrap-20171003.tar.gz
    - wget https://dl.google.com/go/go1.11.src.tar.gz
    - echo "${SHA}" > shasum.txt
    - echo "${SHA2}" >> shasum.txt
    - sha256sum -c shasum.txt
  artifacts:
    paths:
      - go1.4-bootstrap-20171003.tar.gz
      - go1.11.src.tar.gz
    expire_in: 5 hours
  only:
    refs:
      - bootstrap

build:debianish:amd:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/debian:latest
  dependencies:
    - download:bootstrap
  variables:
    GIT_STRATEGY: none
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    GOROOT_BOOTSTRAP: /opt/bootstrap
  before_script:
    - apt-get update
    - apt-get install -y gcc openssl tar ca-certificates
    - tar -zxf go1.4-bootstrap-20171003.tar.gz -C /tmp
    - mkdir -p /opt/bootstrap
    - mv /tmp/go /opt/bootstrap
    - tar -xzf go1.11.src.tar.gz -C /usr/local
  script:
    - cd /opt/bootstrap/src
    - chmod +x make.bash
    - ./make.bash
    - cd /usr/local/go/src
    - chmod +x make.bash
    - ./make.bash --no-clean
    - export GOROOT_BOOTSTRAP=/usr/local/go
    - export PATH="/usr/local/go/bin:$PATH"
    - chmod +x bootstrap.bash
    - ./bootstrap.bash
    - cd ${CI_PROJECT_DIR}
    - cp /usr/local/go-linux-amd64-bootstrap.tbz ${CI_PROJECT_DIR}/bootstrap.tbz
  artifacts:
    paths:
      - bootstrap.tbz
    expire_in: 30 days
  tags:
    - native-amd64

build:debianish:arm:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/debian:latest
  dependencies:
    - download:bootstrap
  variables:
    GIT_STRATEGY: none
    GOOS: linux
    GOARCH: arm64
    CGO_ENABLED: 0
    GOROOT_BOOTSTRAP: /opt/bootstrap
  before_script:
    - apt-get update
    - apt-get install -y gcc openssl tar ca-certificates
    - tar -zxf go1.4-bootstrap-20171003.tar.gz -C /tmp
    - mkdir -p /opt/bootstrap
    - mv /tmp/go /opt/bootstrap
    - tar -xzf go1.11.src.tar.gz -C /usr/local
  script:
    - cd /opt/bootstrap/src
    - chmod +x make.bash
    - ./make.bash
    - cd /usr/local/go/src
    - chmod +x make.bash
    - ./make.bash --no-clean
    - export GOROOT_BOOTSTRAP=/usr/local/go
    - export PATH="/usr/local/go/bin:$PATH"
    - chmod +x bootstrap.bash
    - ./bootstrap.bash
    - cd ${CI_PROJECT_DIR}
    - cp /usr/local/go-linux-arm64-bootstrap.tbz ${CI_PROJECT_DIR}/bootstrap.tbz
  artifacts:
    paths:
      - bootstrap.tbz
    expire_in: 30 days
  tags:
    - native-aarch64
