stages:
  - pre
  - download

download:versions:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: pre
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache libxml2-utils grep
  script:
    - HTML=$(wget -qO- https://golang.org/dl)
    # For some reason, the build script would not work when running this with a pipe, so for now, it aught to be multi commands...
    - VERSIONS=$(echo ${HTML} | xmllint --html --xpath "//div[contains(@id, 'go') and contains(@class, 'toggle')]/@id" - 2>/dev/null)
    - VERSIONS=$(echo ${VERSIONS} | awk '{print $1 $2}')
    - VERSIONS=$(echo ${VERSIONS} | grep -oP '(?<=go)(([0-9]{0,3}(\.?)){3})')
    - VERSIONS=$(echo ${VERSIONS} | awk '{print $1\n$2}')
    - echo "Fetching checksums for ${VERSIONS}"
    - |
      for VERSION in ${VERSIONS}; do
        echo "Fetching SHA for ${VERSION}"
        OUTPUT=$(echo "${HTML}" | xmllint --html --xpath "//a[contains(@class, 'download') and contains(@href, '${VERSION}.src.tar.gz') and not(contains(@class, 'downloadBox'))]/parent::td/following-sibling::td[5]/tt/text()" - 2>/dev/null)
        echo "SHA ${OUTPUT}"
        echo "${OUTPUT} go${VERSION}.src.tar.gz" >> sha256sum.txt
      done

  artifacts:
    paths:
      - sha256sum.txt
    expire_in: 1 day

download:src:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  variables:
    GIT_STRATEGY: none
  dependencies:
    - download:versions
  before_script:
    - apk add --no-cache coreutils
  script:
    - |
      while read -r line
      do
        echo ${line}
        echo ${line} | awk wget https://dl.google.com/go/go${2}.src.tar.gz
      done <"sha256sum.txt"
    - sha256sum -c sha256sum.txt
  artifacts:
    paths:
      - /*.src.tar.gz
    expire_in: 1 day
